---
title: "Gächter et al (2007, JPE) replication"
description: |
  Reproducing Gächter et al.'s Visualizations.
author:
  - name: Hauke Roggenkamp 
    affiliation: CLICCS
    affiliation_url: https://www.cliccs.uni-hamburg.de/
date: "`r Sys.Date()`"
bibliography: biblio.bib
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: false
    code_folding: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Background

In an attempt to incorporate uncertainty to @GACHTER2017's dynamic public goods game (DPGG), we plan to run a series of remote online experiments using oTree [@oTree]. One of these experiments will replicate Gächter et al.'s NOPUNISH 10-period version as close as possible (given the remote circumstances) to allow for comparisons. 

# Replication

We'll therefore run sessions with groups of four ($i \in I=\{1,2,3,4\}$), an initial endowment of $N_i^1 = 20$ points $T=10$ rounds, a private account with a return of $1$ and a group account with a return of $1.5$ ($\Rightarrow$ MPCR$\equiv \frac{1.5}{4}$), such that:
$$
N_i^{t+1}=N_i^t - c_i^t + \frac{1.5}{4}\sum_{j=1}^4 c_j^t
$$
**Proposition 1:** Consider the public good game with growth as defined above. The unique SPE of the game is such that all players contribute 0 throughout the entire game (both on and off the equilibrium path).^[See @GACHTER2017's Appendix for a formal proof.]


# Incorporating Risk or Uncertainty

The basic idea is that, in every period, there is a (known or unknown)^[TBD] constant probability of an extreme weather event occurring in a group denoted by $r \equiv \frac{5}{16}=31.25$%. Such an extreme weather event can bring about damage $D$. This damage will, however, only occur if the group's contributions are smaller than a threshold $X$, which is half of their endowment, i.e. if:

$$
\sum_{j=1}^4 c_j^t < \frac{1}{2} \sum_{j=1}^4 E_j^t \equiv X
$$
As a consequence, the _expected_ earnings look as follows


$$
N_i^t=
\begin{cases}
N_i^t - c_i^t + \frac{1.5}{4}\sum_{j=1}^4 c_j^t, & \text{if}\ \sum_{j=1}^4 c_j^t \geq \frac{1}{2} \sum_{j=1}^4 E_j^t\\
N_i^t - c_i^t + \frac{1.5}{4}\sum_{j=1}^4 c_j^t -rD, & \text{else}
\end{cases}
$$

With $D=0$ the game collapses to @GACHTER2017's model. The first derivative yields $-1$ implying that the individually rational contribution $c_{FC}^t=0$. 
If $A=4$ denotes the number of players and $C^t$ the aggregate contribution with $C^t=\sum_{j=1}^{A}c_j^t$, the aggregate payoff with $D=0$ is described by:

\begin{align}
\sum_{j=1}^{A}N_j^{t+1} & =\sum_{j=1}^{A}N_j^t - C^t + A \cdot \frac{1.5}{4} \cdot C^t\\
&=\sum_{j=1}^{A}N_j^t + C^t(4 \cdot \frac{1.5}{4} - 1) \\
&=\sum_{j=1}^{A}N_j^t + \frac{C^t}{2}
\end{align}

The collectively rational (that is, the efficient) contribution is $C_{FC}^t=\sum_{j=1}^{A}N_j^t$ because the first derivative is strictly positive.

As a consequence, the game is a dilemma where the individual and collective interest are in conflict.

Incorporating $D>0$, we want the game to remain a dilemma in which and observe whether positive contributions evolve despite contrasting incentives. As a consequence, we have to set $D$ such that freeriding ($c_i^t=0$ for all $i$) and risking to suffer that damage (LHS) remains more attractive than any contribution ($\bar c^t \geq \frac{\bar{N}^t}{2}$) that leads to damage control (RHS).

\begin{align}
N_i^t rD &> N_i^t - \bar{c}^t + A \cdot \frac{1.5}{4} \bar{c}^t \\
N_i^t (rD-1) &> \frac{\bar{c}^t}{2}
\end{align}



## The last period

There are two cases where $i$'s contribution is not pivotal, that is, where the threshold $X$ is (not) reached no matter $i$'s action. If $\sum_{j \neq i}^4 c_j^t \geq X$, the other group members' contributions are large enough to prevent damage. $i$ therefore faces the strategic environment of a regular public goods game where freeriding ($c_i^t=0$) is her best response. If $\sum_{j \neq i}^4 c_j^t + E_i^t < X$, $i$'s endowment is too small to prevent the damage in case of an extreme weather event. She can then just as well give up and freeride with ($c_i^t=0$) to maximize her payoff.

But what is the best thing to do in those cases, where $i$'s contribution can make a difference in damage control, that is, where $\sum_{j \neq i}^4 c_j^t < X < \sum_{j \neq i}^4 c_j^t + E_i^t$? In these cases, $i$ can contribute anything in  between $0 \leq c_i^t \leq X-\sum_{j \neq i}^4 c_j^t$ (the upper limit is the bare minimum required to prevent damages. 

But how much is $i$ actually willing to contribute? $i$ will contribute as long as her earnings from these contributions with successful damage control (LHS) are larger than her reduced earnings from $c_i^t=0$ with expected damage (RHS).

\begin{align}
N_i^t - c_i^t + \frac{1.5}{4}\sum_{j=1}^4 c_j^t & \geq 
 N_i^t + \frac{1.5}{4}\sum_{j=1}^4 c_j^t-rD\\
 
N_i^t - c_i^t \Big(1-\frac{1.5}{4}\Big) + \frac{1.5}{4}\sum_{j\neq i}^4 c_j^t & \geq 
 N_i^t + \frac{1.5}{4}\sum_{j\neq i}^4 c_j^t-rD\\
 
- c_i^t\Big(1-\frac{1.5}{4}\Big) & \geq -rD\\ 

c_i^t & \leq \frac{rD}{1-\frac{1.5}{4}}\\ 

c_i^t & \leq \frac{D}{2} \; \text{ with }r=\frac{5}{16}\\ 
\end{align}

There are two things to note. First and unsurprisingly, the maximal contribution increases in risk and Damage. Second and given the MPCR and the (indeed artificial) risk level, the maximum amount any player would contribute is half the damage they would have suffered due to an extreme weather event if they had not reached the threshold. It is important to remember that they only make that contribution if their contribution is pivotal in controlling the damage. 

Because the game is symmetrical and because it requires every player to contribute at least half of her endowment to control the damage, there is a Nash equilibrium where each player contributes $c_i^t = \frac{1}{2} N_i^t$ if $D_i^t \geq N_i^t$. 

If players cannot make any debt (limited liability), the damage cannot be larger than their endowment. In that case, the players are indifferent in contributing nothing or exactly half of their endowments. If the risk was larger than $31.25$%, positive contributions (that is $c_i^t = \frac{1}{2} N_i^t$) become more likely in the last round.