---
title: "Gächter et al (2007, JPE) replication"
description: |
  Reproducing Gächter et al.'s Visualizations.
author:
  - name: Hauke Roggenkamp 
    affiliation: CLICCS
    affiliation_url: https://www.cliccs.uni-hamburg.de/
date: "`r Sys.Date()`"
bibliography: biblio.bib
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: false
    code_folding: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Background

In an attempt to incorporate uncertainty to @GACHTER2017's dynamic public goods game (DPGG), we plan to run a series of remote online experiments using oTree [@oTree]. One of these experiments will replicate Gächter et al.'s NOPUNISH 10-period version as close as possible (given the remote circumstances) to allow for comparisons. 

# Replication

We'll therefore run sessions with groups of four ($i \in I=\{1,2,3,4\}$), an initial endowment of $N_i^1 = 20$ points $T=10$ rounds, a private account with a return of $1$ and a group account with a return of $1.5$ ($\Rightarrow$ MPCR$\equiv \frac{1.5}{4}$), such that:
$$
N_i^{t+1}=N_i^t - c_i^t + \frac{1.5}{4}\sum_{j=1}^4 c_j^t
$$
**Proposition 1:** Consider the public good game with growth as defined above. The unique SPE of both the game without punishment and with punishment is such that all players contribute 0 throughout the entire game (both on and off the equilibrium path).^[See @GACHTER2017's Appendix for a formal proof.]


# Incorporating Risk or Uncertainty

The basic idea is that, in every period, there is a (known or unknown)^[TBD] constant probability of an extreme weather event occurring in a group denoted by $r \equiv \frac{1}{3}$. Such an extreme weather event can bring about damage (denoted as $d\equiv\frac{1}{2}$), i.e. cut each group member's earnings $N_i^{t+1}$ in half. This damage will, however, only occur if the group's contributions are smaller than a threshold $X$, which is half of their endowment, i.e. if:

$$
\sum_{j=1}^4 c_j^t < \frac{1}{2} \sum_{j=1}^4 E_j^t \equiv X
$$
As a consequence, the _expected_ earnings look as follows


$$
\mathbb{E}\big[N_i^t\big]=
\begin{cases}
N_i^t - c_i^t + \frac{1.5}{4}\sum_{j=1}^4 c_j^t, & \text{if}\ \sum_{j=1}^4 c_j^t \geq \frac{1}{2} \sum_{j=1}^4 E_j^t\\
\Big(N_i^t - c_i^t + \frac{1.5}{4}\sum_{j=1}^4 c_j^t\Big) \Big(1-r(1-d)\Big), & \text{else}
\end{cases}
$$

with $\Big(1-r(1-d)\Big)=\frac{5}{6}$ in our setting.

## The last period without inequality

Let's consider the artificial case of risk neutral players and symmetric endowments during the last period to dive deeper into the players' strategic environment. What is the best response $c_i \in BR_i(c_{-i})$, i.e. the optimal contribution of $i$ given the contributions of all $j \neq i$?

There are two cases where $i$'s contribution is not pivotal, that is, where the threshold $X$ is (not) reached no matter $i$'s action. If $\sum_{j \neq i}^4 c_j^t \geq X$, the other group members' contributions are large enough to prevent damage. $i$ therefore faces the strategic environment of a regular public goods game where freeriding ($c_i^t=0$) is her best response. If $\sum_{j \neq i}^4 c_j^t + E_i^t < X$, $i$'s endowment is too small to prevent the damage in case of an extreme weather event. She can then just as well give up and freeride with ($c_i^t=0$) to maximize her payoff.

But what is the best thing to do in those cases, where $i$'s contribution can make a difference in damage control, that is, where $\sum_{j \neq i}^4 c_j^t < X < \sum_{j \neq i}^4 c_j^t + E_i^t$? In these cases, $i$ will either contribute nothing ($c_i^t=0$) or the bare minimum to prevent expected damages ($c_i^t= X-\sum_{j \neq i}^4 c_j^t$). 

$i$ will contribute as long as her earnings from these contributions with successful damage control (LHS) are larger than her reduced earnings with damage (RHS).


\begin{align*}
N_i^t - c_i^t + \frac{1.5}{4}\sum_{j=1}^4 c_j^t & \geq 
 \Big(1-r(1-d)\Big)\Big(N_i^t + \frac{1.5}{4}\sum_{j=1}^4 c_j^t\Big)\\

N_i^t - c_i^t(1-\frac{1.5}{4}) + \frac{1.5}{4}\sum_{j\neq i}^4 c_j^t & \geq 
 \Big(1-r(1-d)\Big) \Big(N_i^t + \frac{1.5}{4}\sum_{j\neq i}^4 c_j^t\Big)\\

-c_i^t(1-\frac{1.5}{4}) & \geq 
\Big(-r(1-d)\Big) \Big(N_i^t + \frac{1.5}{4}\sum_{j\neq i}^4 c_j^t\Big)\\

c_i^t & \leq \frac{r(d-1)}{\frac{1.5}{4} - 1} \Big(N_i^t + \frac{1.5}{4}\sum_{j\neq i}^4 c_j^t\Big)\\

c_i^t & \leq \frac{8}{30} N_i^t + \frac{1}{10}\sum_{j\neq i}^4 c_j^t\\

\end{align*}


Given the others' contributions, $c_i^t$ depends on the income $i$ would lose if the group fails to control the damage (and the fixed parameters $r$, $d$ as well as the MPCR).

Because this is a symmetric game (by assumption), we can set $c_i^t=c_j^t=c^t$ and find that the maximal contribution players would be willing to make falls short the threshold:

\begin{align*}
c^t & = \frac{8}{30} N^t + \frac{3}{10} c^t\\
\frac{7}{10}c^t & = \frac{8}{30} N^t\\
c^t & = \frac{8}{21} N^t < \frac{N^t}{2}\\
\Rightarrow c^* & = 0
\end{align*}

Because each individual's maximum contribution is smaller than half of her Endowment, the extreme weather event's damage is inevitable. As a consequence, the individuals do not contribute in the first place.

## The last period with inequality

(How) does this change if endowments are heterogeneous?


## Any period with inequality

...