---
title: "Create Rooms for oTree Sessions"
description: |
  A new article created using the Distill format.
author:
  - name: Hauke Roggenkamp 
    url: https://github.com/Howquez
    affiliation: CLICCS
    affiliation_url: https://www.cliccs.uni-hamburg.de/
date: "`r Sys.Date()`"
bibliography: ../biblio.bib
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(stringi)
library(magrittr)
library(data.table)
```

This little script aims to write some random tokens that can be used to generate oTree [ROOMS](https://otree.readthedocs.io/en/latest/rooms.html) with persistent identifiers. These can be used to merge payoffs with participants.

```{r}
strings <- stri_rand_strings(n = 200,
                  length = 8,
                  pattern = "[A-Za-z0-9]") %>%
  data.table()

write.table(strings,
          file = "../../../oTree/_rooms/test.txt",
          col.names = FALSE,
          row.names = FALSE,
          quote = FALSE)
```

