# Generated by Django 2.2.12 on 2020-11-12 09:55

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dPGG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contribution',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
