# Generated by Django 2.2.12 on 2020-11-12 10:29

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dPGG', '0002_auto_20201112_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contribution',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
