# Generated by Django 2.2.12 on 2020-11-12 11:33

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dPGG', '0003_auto_20201112_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='endowment',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
