# Generated by Django 2.2.12 on 2020-11-13 13:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dPGG', '0004_auto_20201112_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gain',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
