# Generated by Django 2.2.12 on 2020-11-13 13:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dPGG', '0005_player_gain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gain',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
