# Generated by Django 2.2.12 on 2020-11-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dPGG', '0006_auto_20201113_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gain',
        ),
    ]
