# Generated by Django 2.2.12 on 2020-11-14 12:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dPGG', '0007_remove_player_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gain',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
