# Generated by Django 2.2.12 on 2020-11-14 12:38

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dPGG', '0009_auto_20201114_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='individual_share',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='endowment',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
