# Generated by Django 2.2.12 on 2020-11-14 12:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dPGG', '0010_auto_20201114_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gain',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
