# Generated by Django 2.2.12 on 2020-11-17 11:04

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dPGG', '0011_auto_20201114_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='disaster',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
