# Generated by Django 2.2.12 on 2020-11-17 11:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('dPGG', '0012_subsession_disaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='disaster',
        ),
        migrations.AddField(
            model_name='group',
            name='disaster',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
